# Scraper for the OCCRP web site.
# The goal is not to download all HTML, but only PDFs & other documents
# linked from the page as proof.
name: meduza_headers

# A title for display in the UI:
description: 'Headers from articles on meduza.io'

# Uncomment to run this scraper automatically:
schedule: monthly
delay: 1
stealthy: true
pipeline:

  init:
    # This first stage will get the ball rolling with a seed URL.
    method: seed
    params:
      urls:
        - https://meduza.io/
    handle:
      pass: fetch

  fetch:
    # Download the seed page
    method: fetch
    params:
      # These rules specify which pages should be scraped or included:
      rules:
        or:
          - pattern: 'https://meduza.io/news/$'
          - pattern: 'https://meduza.io/feature/'
          - pattern: 'https://meduza.io/shapito/'
          - pattern: 'https://meduza.io/short/'
          - pattern: 'https://meduza.io/brand/'

    handle:
      pass: parse

  parse:
    # Parse the scraped pages to find if they contain additional links.
    method: parse
    params:
      store:
        and:
          - pattern: 'https://meduza.io/news/$'
          - pattern: 'https://meduza.io/feature/$'
          - pattern: 'https://meduza.io/shapito/$'
          - pattern: 'https://meduza.io/short/$'
          - pattern: 'https://meduza.io/brand/$'
    handle:
      # this makes it a recursive web crawler:
      store: extractdata
      fetch: fetch
  
  extractdata:
    # Parse the scraped pages to extract useful information
    method: example.meduza_headers:extractdata
    handle:
      pass: store

  store:
    # Store the crawled documents to a directory
    method: db
    params:
      table: "meduza_headers"
      unique:
        - url